name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432

    steps:
      # 1. Checkout du code du repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configuration de JDK 11 pour le build Maven
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # 3. Mise en cache des dépendances Maven
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Exécution du build Maven (compilation, tests unitaires, génération du fichier .jar)
      - name: Build avec Maven
        run: mvn clean install

      # 5. Exécution des tests unitaires
      - name: Exécuter les tests unitaires
        run: mvn test -Dtest=**/*Test.java

      # 6. Attendre que la base de données PostgreSQL soit prête
      - name: Attendre que la base de données soit prête
        run: |
          sleep 10 # Wait for PostgreSQL to start

      # 7. Exécution des tests d'intégration
      - name: Exécuter les tests d'intégration
        run: mvn verify -DskipUnitTests -Dtest=**/*IntegrationTest.java

      # 8. Exécution des tests end-to-end (si applicable)
      - name: Exécuter les tests E2E
        run: mvn verify -De2eTests -Dtest=**/*E2eTest.java

      # 9. Exécution des tests de sécurité (OWASP Dependency Check)
      - name: Exécuter OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check

      # 10. Exécution du rapport de couverture de code Jacoco
      - name: Exécuter le rapport Jacoco
        run: mvn jacoco:report

      # 11. Vérification que le fichier .jar est bien généré
      - name: Vérifier si le fichier .jar existe
        run: |
          ls -lh target/*.jar

      # 12. Construction de l'image Docker
      - name: Construire l'image Docker
        run: docker build -t my-app .  # Le point fait référence au répertoire courant


      # 13. Déploiement automatique sur Render
      - name: Trigger Render deployment
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d '{}' \
          https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys

      # 14. Scan SonarCloud (optionnel, commenté ici)
      # - name: Scan SonarCloud
      # env:
      #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # run: mvn verify sonar:sonar -Dsonar.projectKey=prod_logiciel -Dsonar.organization=ALEX67U -Dsonar.host.url=https://sonarcloud.io
